--- #YAML:1.0
name:                       Labyrinth::Plugin::Album
version:                    1.00
abstract:                   Album plugin for the Labyrinth framework
author:
  - Barbie <barbie@cpan.org>

license:                    artistic_2
distribution_type:          module
installdirs:                site

requires:
  Image::Size:              0
  Labyrinth:                5.10
  Labyrinth::Plugin::Hits:  5.09
recommends:
  Test::More:               0.70
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
  Test::CPAN::Meta:         0.18
  Test::CPAN::Meta::JSON:   0.10
build_requires:
  Test::More:               0.01

provides:
  Labyrinth::Plugin::Album:
    file:     lib/Labyrinth/Plugin/Album.pm
    version:  1.00

no_index:
  directory:
    - examples
    - t
    - vhost

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Plugin-Album

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
