--- #YAML:1.0
name:                       Labyrinth-Plugin-Album
version:                    1.07
abstract:                   Album plugin for the Labyrinth framework
author:
  - Barbie <barbie@cpan.org>

license:                    artistic_2
distribution_type:          module
installdirs:                site

requires:
  perl:                     5.006
  File::Path:               0
  Image::Size:              0
  Labyrinth:                5.14
  Labyrinth::Plugin::Hits:  5.09
recommends:
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  IO::File:                 0
  Labyrinth::Test::Harness: 1.02
  Test::More:               0.70

provides:
  Labyrinth::Plugin::Album:
    file:     lib/Labyrinth/Plugin/Album.pm
    version:  1.07
  Labyrinth::Plugin::Album::Pages:
    file:     lib/Labyrinth/Plugin/Album/Pages.pm
    version:  1.07
  Labyrinth::Plugin::Album::Photos:
    file:     lib/Labyrinth/Plugin/Album/Photos.pm
    version:  1.07

no_index:
  directory:
    - examples
    - t
    - vhost

resources:
  homepage:   http://labyrinth.missbarbell.co.uk
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Plugin-Album
  repository: http://github.com/barbie/labyrinth-plugin-album

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
